#ifndef NETPLEX_TWEAKS_H
#define NETPLEX_TWEAKS_H

#ifndef NETPLEX_SELECT_FDS_HASHTABLE_MODULUS
#define NETPLEX_SELECT_FDS_HASHTABLE_MODULUS 101
#endif /* !NETPLEX_SELECT_FDS_HASHTABLE_MODULUS */

#ifndef NETPLEX_READ_STREAM_BUFFER_SIZE
#define NETPLEX_READ_STREAM_BUFFER_SIZE 256u
#endif /* !NETPLEX_READ_STREAM_BUFFER_SIZE */

#endif /* NETPLEX_TWEAKS_H */
