#ifndef NETPLEX_TWEAKS_H
#define NETPLEX_TWEAKS_H

#ifndef NETPLEX_SELECT_FDS_HASHTABLE_MODULUS
#define NETPLEX_SELECT_FDS_HASHTABLE_MODULUS 101
#endif /* !NETPLEX_SELECT_FDS_HASHTABLE_MODULUS */

#endif /* NETPLEX_TWEAKS_H */
